import React from 'react';
import { motion } from 'framer-motion';
import { 
  Download, 
  RotateCcw, 
  Home,
  CheckCircle,
  AlertTriangle,
  Lightbulb,
  TrendingUp,
  Award
} from 'lucide-react';
import { useAppStore } from '../lib/store';

const ResultsScreen: React.FC = () => {
  const { 
    currentAssessment, 
    currentEssay,
    selectedCourse,
    setScreen,
    resetAssessment
  } = useAppStore();

  if (!currentAssessment) {
    return (
      <div style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <p>No assessment results</p>
      </div>
    );
  }

  const getBandColor = (score: number) => {
    if (score >= 7) return '#10b981';
    if (score >= 5) return '#f59e0b';
    return '#ef4444';
  };

  const handleExport = () => {
    // Generate PDF report
    const report = generateTextReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `assessment-${currentEssay?.studentName || 'essay'}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateTextReport = () => {
    return `
AWE Desktop - Assessment Report
================================
Date: ${new Date().toLocaleDateString()}
Course: ${selectedCourse?.name || 'N/A'}
Student: ${currentEssay?.studentName || 'N/A'}
Student ID: ${currentEssay?.studentId || 'N/A'}

OVERALL BAND: ${currentAssessment.overallBand}

CRITERIA SCORES:
${currentAssessment.criteria.map(c => 
  `- ${c.name}: ${c.band} (${c.score}/${c.maxScore})`
).join('\n')}

FEEDBACK:
${currentAssessment.criteria.map(c => 
  `${c.name}:\n  ${c.feedback}`
).join('\n\n')}

STRENGTHS:
${currentAssessment.strengths.map(s => `• ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${currentAssessment.improvements.map(i => `• ${i}`).join('\n')}

SUGGESTIONS:
${currentAssessment.suggestions.map(s => `• ${s}`).join('\n')}

---
Generated by AWE Desktop
Developed by Dr. Waleed Mandour, 2026
Sultan Qaboos University
    `;
  };

  return (
    <div style={{
      width: '100%',
      height: '100%',
      background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden'
    }}>
      {/* Header */}
      <div style={{
        padding: '24px 40px',
        background: 'linear-gradient(135deg, #1a5f2a 0%, #0d3318 100%)',
        color: 'white'
      }}>
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <div>
            <h1 style={{
              fontSize: '24px',
              fontWeight: 700,
              marginBottom: '4px'
            }}>
              Assessment Results
            </h1>
            <p style={{ fontSize: '14px', opacity: 0.8 }}>
              {selectedCourse?.name} • {currentEssay?.studentName || 'Anonymous'}
            </p>
          </div>
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: 'spring', stiffness: 200 }}
            style={{
              background: '#c9a227',
              borderRadius: '16px',
              padding: '16px 32px',
              textAlign: 'center'
            }}
          >
            <p style={{ fontSize: '12px', opacity: 0.8 }}>Overall Band</p>
            <p style={{ fontSize: '36px', fontWeight: 700 }}>
              {currentAssessment.overallBand}
            </p>
          </motion.div>
        </div>
      </div>

      {/* Content */}
      <div style={{
        flex: 1,
        padding: '24px 40px',
        overflow: 'auto'
      }}>
        {/* Criteria Scores */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(4, 1fr)',
          gap: '16px',
          marginBottom: '24px'
        }}>
          {currentAssessment.criteria.map((criterion, index) => (
            <motion.div
              key={criterion.name}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              style={{
                background: 'white',
                borderRadius: '12px',
                padding: '20px',
                textAlign: 'center',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
              }}
            >
              <p style={{
                fontSize: '13px',
                color: '#64748b',
                marginBottom: '8px'
              }}>
                {criterion.name}
              </p>
              <p style={{
                fontSize: '32px',
                fontWeight: 700,
                color: getBandColor(criterion.score),
                marginBottom: '4px'
              }}>
                {criterion.band}
              </p>
              <div style={{
                height: '4px',
                background: '#e2e8f0',
                borderRadius: '2px',
                overflow: 'hidden'
              }}>
                <div style={{
                  width: `${(criterion.score / criterion.maxScore) * 100}%`,
                  height: '100%',
                  background: getBandColor(criterion.score)
                }} />
              </div>
            </motion.div>
          ))}
        </div>

        {/* Detailed Feedback */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: '2fr 1fr',
          gap: '24px'
        }}>
          {/* Left Column - Detailed Feedback */}
          <div>
            {currentAssessment.criteria.map((criterion, index) => (
              <motion.div
                key={criterion.name}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 + index * 0.1 }}
                style={{
                  background: 'white',
                  borderRadius: '12px',
                  padding: '20px',
                  marginBottom: '16px',
                  boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
                }}
              >
                <div style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: '12px'
                }}>
                  <h3 style={{ fontSize: '16px', fontWeight: 600, color: '#1e293b' }}>
                    {criterion.name}
                  </h3>
                  <span style={{
                    background: `${getBandColor(criterion.score)}20`,
                    color: getBandColor(criterion.score),
                    padding: '4px 12px',
                    borderRadius: '20px',
                    fontSize: '13px',
                    fontWeight: 600
                  }}>
                    Band {criterion.band}
                  </span>
                </div>
                <p style={{ fontSize: '14px', color: '#64748b', lineHeight: 1.6 }}>
                  {criterion.feedback}
                </p>
              </motion.div>
            ))}
          </div>

          {/* Right Column - Strengths & Improvements */}
          <div>
            {/* Strengths */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.6 }}
              style={{
                background: '#f0fdf4',
                borderRadius: '12px',
                padding: '20px',
                marginBottom: '16px',
                border: '1px solid #bbf7d0'
              }}
            >
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                marginBottom: '12px'
              }}>
                <CheckCircle size={18} color="#16a34a" />
                <h3 style={{ fontSize: '15px', fontWeight: 600, color: '#166534' }}>
                  Strengths
                </h3>
              </div>
              <ul style={{ paddingLeft: '20px', margin: 0 }}>
                {currentAssessment.strengths.map((strength, i) => (
                  <li key={i} style={{
                    fontSize: '13px',
                    color: '#166534',
                    marginBottom: '8px',
                    lineHeight: 1.5
                  }}>
                    {strength}
                  </li>
                ))}
              </ul>
            </motion.div>

            {/* Improvements */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.7 }}
              style={{
                background: '#fef3c7',
                borderRadius: '12px',
                padding: '20px',
                marginBottom: '16px',
                border: '1px solid #fde68a'
              }}
            >
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                marginBottom: '12px'
              }}>
                <TrendingUp size={18} color="#d97706" />
                <h3 style={{ fontSize: '15px', fontWeight: 600, color: '#92400e' }}>
                  Areas to Improve
                </h3>
              </div>
              <ul style={{ paddingLeft: '20px', margin: 0 }}>
                {currentAssessment.improvements.map((improvement, i) => (
                  <li key={i} style={{
                    fontSize: '13px',
                    color: '#92400e',
                    marginBottom: '8px',
                    lineHeight: 1.5
                  }}>
                    {improvement}
                  </li>
                ))}
              </ul>
            </motion.div>

            {/* Suggestions */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.8 }}
              style={{
                background: '#eff6ff',
                borderRadius: '12px',
                padding: '20px',
                border: '1px solid #bfdbfe'
              }}
            >
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                marginBottom: '12px'
              }}>
                <Lightbulb size={18} color="#2563eb" />
                <h3 style={{ fontSize: '15px', fontWeight: 600, color: '#1e40af' }}>
                  Suggestions
                </h3>
              </div>
              <ul style={{ paddingLeft: '20px', margin: 0 }}>
                {currentAssessment.suggestions.map((suggestion, i) => (
                  <li key={i} style={{
                    fontSize: '13px',
                    color: '#1e40af',
                    marginBottom: '8px',
                    lineHeight: 1.5
                  }}>
                    {suggestion}
                  </li>
                ))}
              </ul>
            </motion.div>
          </div>
        </div>

        {/* Model Info */}
        <div style={{
          marginTop: '24px',
          padding: '12px 16px',
          background: '#f1f5f9',
          borderRadius: '8px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          fontSize: '13px',
          color: '#64748b'
        }}>
          <Award size={16} />
          <span>
            Assessed by {currentAssessment.llmModel} via {currentAssessment.llmProvider} in {Math.round(currentAssessment.processingTime / 1000)}s
          </span>
        </div>
      </div>

      {/* Footer */}
      <div style={{
        padding: '16px 40px',
        background: 'white',
        borderTop: '1px solid #e2e8f0',
        display: 'flex',
        justifyContent: 'space-between'
      }}>
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={() => {
            resetAssessment();
            setScreen('welcome');
          }}
          style={{
            background: 'transparent',
            border: '1px solid #e2e8f0',
            padding: '10px 20px',
            borderRadius: '8px',
            fontSize: '14px',
            fontWeight: 500,
            color: '#64748b',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}
        >
          <Home size={16} />
          Home
        </motion.button>

        <div style={{ display: 'flex', gap: '12px' }}>
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => setScreen('upload')}
            style={{
              background: '#f1f5f9',
              border: 'none',
              padding: '10px 20px',
              borderRadius: '8px',
              fontSize: '14px',
              fontWeight: 500,
              color: '#64748b',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            <RotateCcw size={16} />
            New Assessment
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleExport}
            style={{
              background: '#1a5f2a',
              border: 'none',
              padding: '10px 20px',
              borderRadius: '8px',
              fontSize: '14px',
              fontWeight: 500,
              color: 'white',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            <Download size={16} />
            Export Report
          </motion.button>
        </div>
      </div>
    </div>
  );
};

export default ResultsScreen;
